name: Setup Node.js
description: Setup Node.js and pnpm

inputs:
  registry-url:
    # ref: https://github.com/actions/setup-node/blob/1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a/action.yml#L18C5-L18C176
    description: 'Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      with:
        run_install: false

    - name: Get pnpm store path
      id: pnpm-store
      shell: bash
      run: echo "store_path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - name: Setup Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version-file: package.json
        registry-url: ${{ inputs.registry-url }}

    - name: Restore pnpm cache
      uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ${{ steps.pnpm-store.outputs.store_path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install Dependencies
      id: pnpm-install
      shell: bash
      run: pnpm install --frozen-lockfile
      continue-on-error: true

    - name: Archive pnpm store on failure
      if: steps.pnpm-install.outcome == 'failure'
      shell: bash
      run: |
        mkdir -p /home/runner/tmp
        tar -czf /home/runner/tmp/pnpm-store-failure.tar.gz /home/runner/setup-pnpm/node_modules/.bin/store/v10/tmp/
        echo "artifact_path=/home/runner/tmp/pnpm-store-failure.tar.gz" >> $GITHUB_ENV

    - name: Upload pnpm store artifact
      if: steps.pnpm-install.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: pnpm-store-failure
        path: ${{ env.artifact_path }}

    - name: Save pnpm cache if main branch
      if: github.ref_name == 'main'
      id: save-pnpm-cache
      uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ${{ steps.pnpm-store.outputs.store_path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
