name: Setup Node.js
description: Setup Node.js and pnpm

inputs:
  registry-url:
    # ref: https://github.com/actions/setup-node/blob/1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a/action.yml#L18C5-L18C176
    description: "Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN."
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        run_install: false

    - name: Get pnpm store path
      id: pnpm-store
      shell: bash
      run: echo "store_path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - name: Setup Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version-file: package.json
        registry-url: ${{ inputs.registry-url }}

    - name: Restore pnpm cache
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ steps.pnpm-store.outputs.store_path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Save pnpm cache if main branch
      if: github.ref_name == 'main'
      id: save-pnpm-cache
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ steps.pnpm-store.outputs.store_path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
